GRANT SELECT ON SCHEMA DEMOUSER00 TO _SYS_REPO WITH GRANT OPTION;
GRANT INSERT ON SCHEMA DEMOUSER00 TO _SYS_REPO WITH GRANT OPTION;
GRANT UPDATE ON SCHEMA DEMOUSER00 TO _SYS_REPO WITH GRANT OPTION;
GRANT DELETE ON SCHEMA DEMOUSER00 TO _SYS_REPO WITH GRANT OPTION;
GRANT DROP ON SCHEMA DEMOUSER00 TO _SYS_REPO WITH GRANT OPTION;